name: Generate NPM module for CASDK WebAPI

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    services:
      webapi:
        image: "ghcr.io/green-software-foundation/carbon-aware-sdk:pre"
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -sS http://localhost:8080/health"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
      - name: Setup OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Generate client library
        run: openapi-generator-cli generate -i http://localhost:8080/api/v1/swagger.yaml -g typescript-axios -o work -c npm-module-config.json
      - name: Publish NPM library
        working-directory: work
        run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Setup TypeDoc
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Generate documents
        working-directory: work
        run: npx typedoc --options ../casdk-api-typedoc.json --entryPoints index.ts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy_page:
    needs: generate
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
